Repository muesli/gitty, pull requests merged in 2022-02, with the labels that each got.

#34 Show branch track stats for active branches
  branch.go
  git.go
  main.go
  track.go
Labels: enhancement

#35 Bump gamut dependency to v0.3.0
  go.mod
  go.sum
Labels: dependencies

#43 Bump go-git dependency to prevent crash
  go.mod
  go.sum
Labels: bug

#44 Improve usage text
  main.go
Labels: documentation

#45 Prioritize upstream remote over origin
  git.go
Labels: enhancement

#46 Support ssh.github.com as a valid provider
  git.go
Labels: bug
